language: node_js
node_js:
  - 12
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm run export
  - touch out/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  github_token: '186084a75873703316394b95547e05ebcc464ad4'
  local_dir: out #
  on:
    branch: master